### PR TITLE
Update Gemfile.lock

### PR DESCRIPTION
**Pull request by sudoyu**
causes incomplete "submodule update" under a proxy.

### CODE REVIEW

**Comment by d** [comment]
-1.
gemfile has nothing to do with submodules.
This commit merely changes the lock file. I'm pretty sure it doesn't do what you want.

feel free to rebase and re-open if you feel misunderstood.

**Comment by mark-rushakoff** [comment]
@d We've accepted pull requests on other repositories that were also changing submodules from git to https.  AFAIK the issue is that people behind overprotective corporate firewalls can't access git URLs but can access https URLs.

**Comment by d** [comment]
@mark-rushakoff I totally agree with you. But I'm not sure this PR actually changed any submodules ...

**Comment by mark-rushakoff** [comment]
@d I get it now.  It should have been changed in the Gemfile and Gemfile.lock both, probably.

I don't have a firewall behind which to try it out, so I'm not going to personally change anything in HM around that.

**Pull request closed without merging**
